serviceAccount:
  create: true
  name: prometheus

server:
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  
alertmanager:
  enabled: true

nodeExporter:
  enabled: true
